#!/bin/bash
# Double-click this file in Finder to install the application.
#
# It builds the Python environment, creates a real double-clickable app in
# ~/Applications, and offers to schedule a daily data refresh. Everything it
# does is reversible and printed as it happens.
#
# A .command file is the closest macOS gets to "double-click to install"
# without a signed installer package: Finder runs it in Terminal, so the user
# sees exactly what happened and any error stays on screen.

set -u

cd "$(dirname "$0")" || exit 1
PROJECT="$(pwd)"
APP_NAME="FQHC Prospect Intelligence"
APP_DIR="$HOME/Applications/$APP_NAME.app"

printf '\n=== %s ===\n\n' "$APP_NAME"
printf 'Installing from: %s\n\n' "$PROJECT"

# ---------------------------------------------------------------------------
# 1. Python environment
# ---------------------------------------------------------------------------
if [ ! -x "./setup_macos.sh" ]; then
    chmod +x ./setup_macos.sh 2>/dev/null
fi

echo "Step 1 of 3: building the Python environment (a few minutes)..."
if ! ./setup_macos.sh; then
    echo
    echo "Setup failed. Nothing was installed. The messages above say why."
    echo "Press Return to close this window."
    read -r _
    exit 1
fi

PYTHON="$PROJECT/.venv/bin/python"
if [ ! -x "$PYTHON" ]; then
    echo "Expected $PYTHON to exist after setup, but it does not. Stopping."
    read -r _
    exit 1
fi

# ---------------------------------------------------------------------------
# 2. A double-clickable app
# ---------------------------------------------------------------------------
# Hand-built bundle rather than a PyInstaller build: it is a few files, it needs
# no toolchain, and it always runs the current code rather than a frozen copy.
echo
echo "Step 2 of 3: creating the app in ~/Applications..."
rm -rf "$APP_DIR"
mkdir -p "$APP_DIR/Contents/MacOS" "$APP_DIR/Contents/Resources"

cat > "$APP_DIR/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key><string>$APP_NAME</string>
    <key>CFBundleDisplayName</key><string>$APP_NAME</string>
    <key>CFBundleIdentifier</key><string>partners.allstar.fqhc-prospect-intelligence</string>
    <key>CFBundleVersion</key><string>1.0</string>
    <key>CFBundleShortVersionString</key><string>1.0</string>
    <key>CFBundlePackageType</key><string>APPL</string>
    <key>CFBundleExecutable</key><string>launch</string>
    <key>CFBundleIconFile</key><string>icon</string>
    <key>NSHighResolutionCapable</key><true/>
    <key>LSMinimumSystemVersion</key><string>11.0</string>
</dict>
</plist>
PLIST

cat > "$APP_DIR/Contents/MacOS/launch" <<LAUNCH
#!/bin/bash
# Generated by the installer. Runs the app from the checkout it was installed
# from, so a git pull updates the app with no reinstall.
cd "$PROJECT" || exit 1
exec "$PYTHON" -m desktop.main
LAUNCH
chmod +x "$APP_DIR/Contents/MacOS/launch"

if [ -f "$PROJECT/desktop/icon.icns" ]; then
    cp "$PROJECT/desktop/icon.icns" "$APP_DIR/Contents/Resources/icon.icns"
elif [ -f "$PROJECT/desktop/icon.png" ] && command -v sips >/dev/null 2>&1; then
    ICONSET="$(mktemp -d)/icon.iconset"
    mkdir -p "$ICONSET"
    for SIZE in 16 32 128 256 512; do
        sips -z $SIZE $SIZE "$PROJECT/desktop/icon.png" \
            --out "$ICONSET/icon_${SIZE}x${SIZE}.png" >/dev/null 2>&1
        sips -z $((SIZE * 2)) $((SIZE * 2)) "$PROJECT/desktop/icon.png" \
            --out "$ICONSET/icon_${SIZE}x${SIZE}@2x.png" >/dev/null 2>&1
    done
    iconutil -c icns "$ICONSET" -o "$APP_DIR/Contents/Resources/icon.icns" 2>/dev/null
fi

echo "  Created $APP_DIR"

# ---------------------------------------------------------------------------
# 3. Daily refresh
# ---------------------------------------------------------------------------
echo
echo "Step 3 of 3: daily data refresh."
echo "  This runs the pipeline once a day so the prospect data stays current."
echo "  It uses only public sources and takes a few minutes."
echo
printf '  Schedule a daily refresh at 6am? [Y/n] '
read -r ANSWER
case "${ANSWER:-y}" in
    [Nn]*)
        echo "  Skipped. Run this later to enable it:"
        echo "    $PYTHON -m desktop.schedule install --hour 6"
        ;;
    *)
        "$PYTHON" -m desktop.schedule install --hour 6
        ;;
esac

# ---------------------------------------------------------------------------
echo
echo "=== Done ==="
echo
echo "Open the app:      ~/Applications/$APP_NAME"
echo "                   (drag it to your Dock to keep it handy)"
echo "Build the data:    $PYTHON -m pipeline.run"
echo "Daily refresh:     $PYTHON -m desktop.schedule status"
echo
echo "Press Return to close this window."
read -r _
